import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import Layout
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wild Beginnings</title>
        <meta name="Wild Beginnings" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <Layout>
          <div>Lovelace</div>
        </Layout>
      </main> */}
    </div>
  )
}
